# Config file for various conversion technologies.
wind_onshore:
  converter_IV: 'V110'
  converter_III: 'V90'
  converter_II: 'V90'
  converter_I: 'V105'
  resource: 'wind'
  deployment: 'onshore'
  resource_threshold: 4. #m/s
  population_density_threshold_low: 0.
  population_density_threshold_high: 100.
  protected_areas_selection: ['Ia', 'Ib', 'II']
  protected_areas_distance_threshold: 10.
  depth_threshold_low: 0.
  depth_threshold_high: 0.
  altitude_threshold: 1500.
  terrain_slope_threshold: 0.03
  forestry_ratio_threshold: 0.8
  latitude_threshold: 65.

wind_offshore:
  converter_IV: 'V90'
  converter_III: 'V90'
  converter_II: 'V164'
  converter_I: 'V164'
  resource: 'wind'
  deployment: 'offshore'
  resource_threshold: 7. #m/s
  population_density_threshold_low: 0.
  population_density_threshold_high: 100.
  protected_areas_selection: ['Ia', 'Ib', 'II', 'V']
  protected_areas_distance_threshold: 5.
  depth_threshold_low: 0.
  depth_threshold_high: 999.
  altitude_threshold: 0.
  terrain_slope_threshold: 1.
  forestry_ratio_threshold: 1.
  latitude_threshold: 70.
  distance_threshold_min: 22.2
  distance_threshold_max: 222.2 # 111.

wind_floating:
  converter_IV: 'V90'
  converter_III: 'V90'
  converter_II: 'V164'
  converter_I: 'V164'
  resource: 'wind'
  deployment: 'floating'
  resource_threshold: 9. #m/s
  population_density_threshold_low: 0.
  population_density_threshold_high: 100.
  protected_areas_selection: ['Ia', 'Ib', 'II', 'V']
  protected_areas_distance_threshold: 5.
  depth_threshold_low: 200.
  depth_threshold_high: 990.
  altitude_threshold: 0.
  terrain_slope_threshold: 1.
  forestry_ratio_threshold: 1.
  latitude_threshold: 65.
  distance_threshold_min: 23.
  distance_threshold_max: 180.

solar_utility:
  converter: 'DEG15MC'
  resource: 'solar'
  deployment: 'utility'
  resource_threshold: 130. #W/m2
  population_density_threshold_low: 0.
  population_density_threshold_high: 100.
  protected_areas_selection: ['Ia', 'Ib', 'II', 'V']
  protected_areas_distance_threshold: 5.
  depth_threshold_low: 0.
  depth_threshold_high: 0.
  altitude_threshold: 1500.
  terrain_slope_threshold: 0.03
  forestry_ratio_threshold: 0.8
  latitude_threshold: 65.

solar_residential:
  converter: 'DD06M'
  resource: 'solar'
  deployment: 'residential'
  resource_threshold: 100. #W/m2
  population_density_threshold_low: 10.
  population_density_threshold_high: 999999.
  protected_areas_selection: ['Ia', 'Ib', 'II', 'V']
  protected_areas_distance_threshold: 1.
  depth_threshold_low: 0.
  depth_threshold_high: 0.
  altitude_threshold: 3000.
  terrain_slope_threshold: 1.
  forestry_ratio_threshold: 1.
  latitude_threshold: 65.
