# Config file for various conversion technologies.
wind_onshore:
  where: 'onshore'
  filters: ['resource_quality', 'population_density', 'orography', 'forestry', 'water_mask', 'latitude']
  converter_IV: 'V110'
  converter_III: 'E103'
  converter_II: 'V90'
  converter_I: 'E-126'
  resource: 'wind'
  deployment: 'onshore'
  resource_threshold: 4. #m/s
  population_density_threshold_low: 0.
  population_density_threshold_high: 100.
  protected_areas_selection: ['Ia', 'Ib', 'II']
  protected_areas_distance_threshold: 10.
  depth_threshold_low: 0.
  depth_threshold_high: 0.
  altitude_threshold: 1500.
  terrain_slope_threshold: 0.03
  forestry_ratio_threshold: 0.8
  latitude_threshold: 65.

wind_offshore:
  where: 'offshore'
  filters: ['resource_quality', 'bathymetry', 'latitude', 'distance', 'legacy']
  converter_IV: 'V90'
  converter_III: 'V90'
  converter_II: 'V164'
  converter_I: 'V164'
  resource: 'wind'
  deployment: 'offshore'
  resource_threshold: 5. #m/s
  population_density_threshold_low: 0.
  population_density_threshold_high: 100.
  protected_areas_selection: ['Ia', 'Ib', 'II', 'V']
  protected_areas_distance_threshold: 5.
  depth_threshold_low: 0.
  depth_threshold_high: 199.
  altitude_threshold: 0.
  terrain_slope_threshold: 1.
  forestry_ratio_threshold: 1.
  latitude_threshold: 70.
  distance_threshold_min: 22.2
  distance_threshold_max: 222.0 # 111.
  legacy_min: 0.1

wind_floating:
  where: 'offshore'
  filters: ['resource_quality', 'bathymetry', 'latitude', 'distance']
  converter_IV: 'V90'
  converter_III: 'V90'
  converter_II: 'V164'
  converter_I: 'V164'
  resource: 'wind'
  deployment: 'floating'
  resource_threshold: 9. #m/s
  population_density_threshold_low: 0.
  population_density_threshold_high: 100.
  protected_areas_selection: ['Ia', 'Ib', 'II', 'V']
  protected_areas_distance_threshold: 5.
  depth_threshold_low: 200.
  depth_threshold_high: 990.
  altitude_threshold: 0.
  terrain_slope_threshold: 1.
  forestry_ratio_threshold: 1.
  latitude_threshold: 65.
  distance_threshold_min: 23.
  distance_threshold_max: 180.

pv_utility:
  where: 'onshore'
  filters: ['resource_quality', 'population_density', 'orography', 'forestry', 'water_mask', 'latitude']
  converter: 'DEG15MC'
  resource: 'solar'
  deployment: 'utility'
  resource_threshold: 130. #W/m2
  population_density_threshold_low: 0.
  population_density_threshold_high: 100.
  protected_areas_selection: ['Ia', 'Ib', 'II', 'V']
  protected_areas_distance_threshold: 5.
  depth_threshold_low: 0.
  depth_threshold_high: 0.
  altitude_threshold: 1500.
  terrain_slope_threshold: 0.03
  forestry_ratio_threshold: 0.8
  latitude_threshold: 65.

#TODO: adjust pv_residential filters
pv_residential:
  where: 'onshore'
  filters: ['population_density', 'water_mask']
  converter: 'DD06M'
  resource: 'solar'
  deployment: 'residential'
  resource_threshold: 100. #W/m2
  population_density_threshold_low: 10.
  population_density_threshold_high: 999999.
  protected_areas_selection: ['Ia', 'Ib', 'II', 'V']
  protected_areas_distance_threshold: 1.
  depth_threshold_low: 0.
  depth_threshold_high: 0.
  altitude_threshold: 3000.
  terrain_slope_threshold: 1.
  forestry_ratio_threshold: 1.
  latitude_threshold: 65.
