# Path to data folder
#data_path: 'D:/ULg_PhD_work/datasets/resite_ip/'
data_path: '/data/dcradu/resite_ip/'

# Spatial resolution (in degrees) of the potential sites.
spatial_resolution: 0.25
# Start time and end time of the analysis.
time_slice: ['2010-01-01T00:00', '2019-12-31T23:00']
resampling_rate: 3
# Technologies to deploy.
regions: ['EU']
technologies: ['wind_offshore']
deployments: [[468]]
load_coverage: 0.3

siting_params:
  # Defines how \alpha is considered in space and time.
  alpha:
    method: 'load' # 'potentials'
    coverage: 'system' # 'partition'
    smoothing: 'mean' # 'median'
    norm: 'min' # 'max'
  # Time-window length used to compute the criticality indicator. Integer value.
  delta: 1                          # \in \mathbb{N}
  # Threshold
  c: 0.1                            # \in [0, 1]
  # Solution method: BB or HEU or RAND or GRED.
  solution_method:
    neighborhood: 1
    no_iterations: 5000
    no_epochs: 500
    initial_temp: 100.
    no_runs: 30
