# Config file for various conversion technologies.
# technology:
#  where: 'onshore'/'offshore' - NOT TO BE ALTERED
#  filters: filters used to remove candidate locations based on land utilization criteria -
#            to choose from ['water_mask', 'bathymetry', 'distance', 'resource_quality', 'forestry',
#            'population_density', 'orography', 'latitude']
#  converter_IV: converter to be used for class IV winds - set of available converters available at
#                data/transfer_functions/data_wind_turbines.csv
#  converter_III: converter to be used for class III winds
#  converter_II: converter to be used for class II winds
#  converter_I: converter to be used for class I winds
#  resource: NOT TO BE ALTERED
#  deployment: NOT TO BE ALTERED
#  resource_threshold: average wind speed (m/s) under which candidate sites are discarded
#  population_density_threshold_low: lower end of population density threshold limit to discard candidate sites
#  population_density_threshold_high: upper end of population density threshold limit to discard candidate sites
#  depth_threshold_low: lower end of depth threshold limit to discard candidate sites (for offshore)
#  depth_threshold_high: upper end of depth threshold limit to discard candidate sites (for offshore)
#  altitude_threshold: altitude threshold (in m) limit to discard candidate sites
#  terrain_slope_threshold: terrain slope (in %) threshold limit to discard candidate sites
#  forestry_ratio_threshold: forestry threshold (in % of cell area) limit to discard candidate sites
#  latitude_threshold: latitude threshold limit (in degrees) to discard candidate sites

wind_onshore:
  where: 'onshore'
  filters: ['population_density', 'orography', 'water_mask', 'forestry', 'resource_quality', 'latitude']
  converter_IV: 'V110'
  converter_III: 'E103'
  converter_II: 'V90'
  converter_I: 'E-126'
  resource: 'wind'
  deployment: 'onshore'
  resource_threshold: 4. #m/s
  population_density_threshold_low: 0.
  population_density_threshold_high: 200.
  protected_areas_selection: ['Ia', 'Ib', 'II']
  protected_areas_distance_threshold: 10.
  depth_threshold_low: 0.
  depth_threshold_high: 0.
  altitude_threshold: 1500.
  terrain_slope_threshold: 0.03
  forestry_ratio_threshold: 0.8
  latitude_threshold: 65.
  legacy_min: 0.1
  power_density: 8. # MW/sqkm
  land_utilization_factor: 0.3

wind_offshore:
  where: 'offshore'
  filters: ['bathymetry', 'distance']
  converter_IV: 'V90'
  converter_III: 'V90'
  converter_II: 'V164'
  converter_I: 'V164'
  resource: 'wind'
  deployment: 'offshore'
  resource_threshold: 5. #m/s
  population_density_threshold_low: 0.
  population_density_threshold_high: 100.
  protected_areas_selection: ['Ia', 'Ib', 'II', 'V']
  protected_areas_distance_threshold: 5.
  depth_threshold_low: 0.
  depth_threshold_high: 999.
  altitude_threshold: 0.
  terrain_slope_threshold: 1.
  forestry_ratio_threshold: 1.
  latitude_threshold: 70.
  distance_threshold_min: 22.2
  distance_threshold_max: 222.0 # 111.
  legacy_min: 0.1
  power_density: 6. # MW/sqkm
  land_utilization_factor: 0.5

wind_floating:
  where: 'offshore'
  filters: ['resource_quality', 'bathymetry', 'latitude', 'distance']
  converter_IV: 'V90'
  converter_III: 'V90'
  converter_II: 'V164'
  converter_I: 'V164'
  resource: 'wind'
  deployment: 'floating'
  resource_threshold: 9. #m/s
  population_density_threshold_low: 0.
  population_density_threshold_high: 100.
  protected_areas_selection: ['Ia', 'Ib', 'II', 'V']
  protected_areas_distance_threshold: 5.
  depth_threshold_low: 200.
  depth_threshold_high: 990.
  altitude_threshold: 0.
  terrain_slope_threshold: 1.
  forestry_ratio_threshold: 1.
  latitude_threshold: 65.
  distance_threshold_min: 23.
  distance_threshold_max: 180.
  legacy_min: 0.1
  power_density: 5. # MW/sqkm
  land_utilization_factor: 0.5

pv_utility:
  where: 'onshore'
  filters: ['resource_quality', 'population_density', 'orography', 'forestry', 'water_mask', 'latitude']
  converter: 'DEG15MC'
  resource: 'solar'
  deployment: 'utility'
  resource_threshold: 130. #W/m2
  population_density_threshold_low: 0.
  population_density_threshold_high: 100.
  protected_areas_selection: ['Ia', 'Ib', 'II', 'V']
  protected_areas_distance_threshold: 5.
  depth_threshold_low: 0.
  depth_threshold_high: 0.
  altitude_threshold: 1500.
  terrain_slope_threshold: 0.03
  forestry_ratio_threshold: 0.8
  latitude_threshold: 65.
  legacy_min: 0.1
  power_density: 5. # MW/sqkm
  land_utilization_factor: 0.5

pv_residential:
  where: 'onshore'
  filters: ['population_density', 'water_mask']
  converter: 'DD06M'
  resource: 'solar'
  deployment: 'residential'
  resource_threshold: 100. #W/m2
  population_density_threshold_low: 10.
  population_density_threshold_high: 999999.
  protected_areas_selection: ['Ia', 'Ib', 'II', 'V']
  protected_areas_distance_threshold: 1.
  depth_threshold_low: 0.
  depth_threshold_high: 0.
  altitude_threshold: 3000.
  terrain_slope_threshold: 1.
  forestry_ratio_threshold: 1.
  latitude_threshold: 65.
  legacy_min: 0.1
  power_density: 5. # MW/sqkm
  land_utilization_factor: 0.5
