# Path to data folder
data_path: 'path_to_data'

# Spatial resolution (in degrees) of the potential sites.
spatial_resolution: 0.25
# Start time and end time of the analysis.
time_slice: ['2018-01-01T00:00', '2018-01-31T23:00']
# Technologies to deploy.
regions: ['BE', 'LT', 'LV', 'EE', 'HR']
technologies: ['wind_offshore']
deployments: [[3], [4], [3], [2], [1]]

siting_params:
  smooth_measure: 'mean'            # median, percentiles
  # Defines how \alpha is considered in space and time.
  alpha: 'load_central'             # load_central, load_partition
  # Normalization procedures (detailed in tools.py). (min, max)
  norm_type: 'max'                  # max, min
  # Time-window length used to compute the criticality indicator. Integer value.
  delta: 1                          # \in \mathbb{N}
  # Threshold
  c: 1                              # < n, \in \mathbb{N}
  # Solution method: BB or HEU or RAND or GRED.
  solution_method:
    SA:
      set: False
      neighborhood: 1
      no_iterations: 100
      no_epochs: 100
      initial_temp: 200.
      p: 0.05
      no_runs: 3
      no_runs_init: 5
      algorithm: 'MIR' # 'MIR', 'SGH'
    SGH:
      set: True
      p: 0.05
      no_runs: 3
      algorithm: 'SGH'