name: resite_ip
channels:
  - conda-forge
  - defaults
dependencies:
  - bottleneck
  - dask
  - scipy
  - toolz
  - xarray
  - geopandas
  - pyyaml
  - xlrd
  - geopy
  - shapely
  - geopy
  - julia
  - pycountry