name: resite_ip
channels:
  - conda-forge
  - defaults
dependencies:
  - bottleneck
  - cdsapi
  - dask
  - matplotlib
  - pyomo
  - scipy
  - toolz
  - xarray
  - geopandas
  - pyyaml
  - xlrd
  - geopy
  - pypsa
  - shapely